# Generated by Django 5.1 on 2024-08-10 15:53

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("things", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="thing",
            name="location",
            field=models.ForeignKey(
                default=24,
                on_delete=django.db.models.deletion.PROTECT,
                to="things.location",
            ),
        ),
    ]
