# Generated by Django 5.1 on 2024-08-12 02:51

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('things', '0002_thing_location'),
    ]

    operations = [
        migrations.AlterField(
            model_name='location',
            name='name',
            field=models.CharField(max_length=64, unique=True),
        ),
        migrations.AlterField(
            model_name='thing',
            name='location',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='things.location'),
        ),
    ]
