# Generated by Django 5.1 on 2024-08-16 01:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('things', '0003_alter_location_name_alter_thing_location'),
    ]

    operations = [
        migrations.AddField(
            model_name='thing',
            name='units',
            field=models.IntegerField(default=1),
        ),
    ]
