# Generated by Django 5.1 on 2025-09-20 20:24

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('things', '0004_thing_units'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='location',
            options={'verbose_name_plural': 'locations'},
        ),
        migrations.AddField(
            model_name='location',
            name='location',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='+', to='things.location'),
        ),
        migrations.AlterField(
            model_name='location',
            name='id',
            field=models.BigAutoField(primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='thing',
            name='units',
            field=models.IntegerField(choices=[(1, 'each'), (2, 'inches'), (3, 'feet'), (4, 'kg'), (5, 'lbs'), (6, 'ounces'), (7, 'liters'), (8, 'grams'), (9, 'milliliters'), (10, 'meters'), (11, 'centimeters'), (12, 'millimeters')], default=1),
        ),
    ]
